config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  root 'uploads#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_many_attached :files
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: %i[destroy]

  def index
    files = []
    Upload.all.each { |u| u.files.each { |f| files << { id: f.record.id, title: f.record.title, file: f, filename: f.filename.to_s } } }
    @files = files.uniq { |f| f[:filename] }
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params)

    if @upload.save
      redirect_to root_path, notice: "File successfully uploaded"
    else
      @upload.files.purge_later
      redirect_to root_path, alert: "An error occurred. Please try again."
    end
  end

  def destroy
    @file.destroy
    @file.files.purge_later
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
      flash[:notice] = "File successfully deleted"
    end
  end

  private

  def upload_params
    params.permit(:title, files: [])
  end

  def set_upload
    @file = Upload.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissable fade show">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
<% end %>

<% if alert %>
<div class="alert alert-warning alert-dismissable fade show">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= alert %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Transfer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/uploads/_upload_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Upload a file</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: upload, local: true) do |f| %>

          <div class="file-upload">
            <div class="form-group">
              <%= f.label :title %><br />
              <%= f.text_field :title, class: 'form-control form-control-sm', required: true %>
            </div>

              <%= f.file_field :files, multiple: true, direct_upload: true, required: true %>
          </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Upload",'data-disable-with' => "Uploading...", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/uploads/index.html.erb
<div class="container show-uploads">
  <h4 class="upload-header">Uploads</h4>
  <button data-toggle='modal' data-target='#exampleModal' type='button' class='btn btn-primary'>New Upload</button>
  <table class="table table-hover">
      <% if @files.any? %>
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Filename</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <% @files.each do |file| %>
          <tr>
            <td><%= file[:title] %></td>
            <td><%= file[:filename] %></td>
            <td><%= link_to "Download", rails_blob_path(file[:file], disposition: 'attachment'), class: "" %></td>
            <td><%= link_to 'Delete', upload_path(file[:id]), method: :delete, data: {confirm: "Are you sure you want to delete this file?"}, class: 'btn btn-danger btn-sm download'  %></td>
          </tr>
        <% end %>
    </tbody>
      <% else %>
        <h4>No file uploaded yet!</h4>
      <% end %>
  </table>
</div>

<%= render "uploads/upload_modal", upload: @upload %>

app/views/uploads/new.html.erb
 <button data-toggle='modal'
      data-target='#exampleModal' type="button">Upload</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Upload a file</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @upload, local: true) do |f| %>

          <div class="file-upload">
            <div class="form-group">
              <%= f.label :title %><br />
              <%= f.text_field :title, class: 'form-control form-control-sm'%>
            </div>
              <label for="file-input">
                 
                  <div id="selected-files"></div>
              </label>
              <%= f.file_field :files, id: "file-input", multiple: true, direct_upload: true, required: true %>
          </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Upload",'data-disable-with' => "Uploading...", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
        <% end %>
    </div>
  </div>
</div>